description: Remote relationship GraphQL query with errors
url: /v1/graphql
status: 200
# Since errorMsg in not non-null we should both return a valid result as well
# as propogate the error the remote server raised.
response:
  data:
    profiles:
      - id: 1
        userBasic:
            id: 1
            username: jane
      - id: 2
        userBasic:
            id: 2
            username: john
      - id: 3
        userBasic:
            id: 3
            username: joe
      - id: 4
        userBasic: null
      - id: 5
        userBasic: null
  errors:
    - locations:
        - [1, 253]
      message: 'Could not find user with id: 4'
      path: [hasura_array_idx_3]
    - locations:
        - [1, 334]
      message: 'Could not find user with id: 5'
      path: [hasura_array_idx_4]
query:
  query: |
    query {
      profiles {
        id
        userBasic(throwError: true) {
          id
          username
        }
      }
    }
